### ISSUE TITLE
Enquête sur une API retournant une adresse dans n'importe quel cas

### ISSUE THREAD

**Issue by GabG02** [av1m/Apartments#18]
**Réalisation d'une enquête concernant le besoin suivant :** 

**Objectif :** Ne pas dupliquer les appels à une API pour la récupération d'adresse dans le cas où aucune adresse n'est récupéré

**Critère d'acceptabilité :** 
1. Lors de la récupération d'adresse avec des coordonnées correspondant à une adresse, l'adresse est traitée et enregistrée dans l'appartement.
2. Lors de la récupération d'adresse avec des coordonnées ne correspondant à aucune adresse précise, une adresse voisine est récupérée et traitée puis enregistrée dans l'appartement.
3. Dans n'importe quel cas, un seul appel à l'API est nécessaire pour récupérer une adresse valide.

commentaire : 
_Merci pour cette précision, cela m’avait échappé. Je ne suis pas emballé par la stratégie adoptée par cette méthode, dans ce cas. Essayer des (lat, long) au hasard en espérant finir par tomber sur une position qui fonctionne est très peu élégant, problème largement aggravé par la nécessité d’une requête réseau pour vérifier à chaque essai. Je ne bloque pas la PR pour ceci, mais mettez en FUTURE une investigation d’une meilleure stratégie. Il doit être possible par exemple de trouver une API qui renvoie l’adresse existante la plus proche d’une position donnée._

_cf : https://github.com/av1m/Apartments/pull/14#issuecomment-622929645_

**Comment by av1m** [comment]
I think [this documentation](https://github.com/av1m/Apartments/blob/master/Doc/packages.adoc#address-generation-for-random-apartment) answers the problems.

However, we can actually go back to what was done and use an API that directly returns a random address to us. However, we will be much more limited in terms of uses and constrained by the API.

In this sense, as mentioned in #14, the API that we use is French, maintained by the "Direction interministérielle du numérique" and returns us real address (in case it is actually possible).
It is better not to recover anything (and try again with other geographic coordinates) than to recover false information (eg recovering a departmental road "D170, 95500")

In addition, we do not need to have an account or use an API key. This does not alter the limitation, and on the contrary it is an API which offers a really large number of calls.

For more information see the section [see detailed documentation on the risk of non-return](https://github.com/av1m/Apartments/blob/master/Doc/packages.adoc#address-generation-for-random-apartment) and [benchmark](https://github.com/av1m/Apartments/blob/master/Doc/packages.adoc#address-generation-for-random-apartment)

**Comment by av1m** [comment]
I think that, following the discussion with [oliviercailloux](https://github.com/oliviercailloux), we can close this issue @MorganeFt
