### ISSUE TITLE
voir SVP JAX-RS client dans cours.

### ISSUE THREAD

**Issue by GabG02** [av1m/Apartments#5]
https://github.com/av1m/Apartments/pull/3#discussion_r410394483

FUTURE (voir Instructions projets pour « FUTURE ») : voir SVP JAX-RS client dans cours.

_Originally posted by @oliviercailloux in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mzk1NjQ1MTQ0/pull_request_reviews/more_threads_

**Comment by clemencecousin** [comment]
Seen in [PR #3](https://github.com/av1m/Apartments/pull/3)
