### ISSUE TITLE
 remplacer paramètre par URI, plus général.

### ISSUE THREAD

**Issue by GabG02** [av1m/Apartments#6]
FUTURE remplacer paramètre par URI, plus général.

https://github.com/av1m/Apartments/pull/3#discussion_r410399835 

_Originally posted by @oliviercailloux in https://github.com/av1m/Apartments/pull/3_

**Comment by clemencecousin** [comment]
Seen in [PR #3](https://github.com/av1m/Apartments/pull/3)

**Comment by GabG02** [comment]
Après discussion avec Olivier Cailloux, la variable de type Path étant déjà définie suffit.
