### ISSUE TITLE
Refaire fonctionnement Retry 

### ISSUE THREAD

**Issue by GabG02** [av1m/Apartments#7]
Cette fct de retry n’a vraiment pas sa place ici, à la réflexion. On peut souhaiter modifier toutes sortes d’options concernant le moyen de requête réseau utilisé (timeout, retries, …), mais ce paramètre ici n’est pas le bon moyen de le faire. En outre, si la requête continue à échouer après plusieurs essais (ce qui sera généralement le cas si elle a échoué après le premier essai), le stack trace généré sera rendu peu lisible par les exceptions en cascade. (OPT)

https://github.com/av1m/Apartments/pull/3#discussion_r411255515

_Originally posted by @oliviercailloux in https://github.com/av1m/Apartments/pull/3_

**Comment by oliviercailloux** [comment]
“Originally posted by @oliviercailloux in #3” Ça s’indique tout seul par une fct de GitHub, ou l’ajoutez-vous à la main ? En tous cas, veuillez voir Mentions dans les instructions projets SVP.

**Comment by GabG02** [comment]
@oliviercailloux 
il s'ajoute tout seul lorsque nous faisons create an issue dans les option d'une discussion d'une pull request 
Il est plus pratique également de rajouter le lien du commentaire (option > copy link) et de l'ajouter (cf "#3 (comment)") --> Cela redirige vers le commentaire et donc vers le morceau de code concerné

**Comment by GabG02** [comment]
cf https://trello.com/c/9eA2z1Gw/6-d%C3%A9velopper-api-pour-la-r%C3%A9cup%C3%A9ration-dadresse

**Comment by GabG02** [comment]
Après conversation avec Olivier Cailloux, le système de Retry est à supprimer : cf modifs : commit 30c1d4ce3d2c3f404e5c7d08b2e8eb3d55273a66
